name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup PHP
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      # Copy .env file for testing
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      # Install PHP dependencies
      # Install PHP dependencies
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Generate application key
      - name: Generate key
        run: php artisan key:generate

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Create an empty database file
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Install Node modules and build assets
      - name: Install Node.js and build assets
        run: |
          npm install --legacy-peer-deps
          npm run build

      # Execute PHPUnit tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit